### ISSUE TITLE
Problem with double use of closure

### ISSUE THREAD

**Issue by aabbtree77** [polydojo/jispy#1]
This code shows the problem with the jispy interpreter:

var makeClosure = function (x) { var func = function (n) {return x+n;}; return func;}, 
      myadderone = null,
      myadderthousand = null;
      myadderone = makeClosure(1);
      myadderthousand = makeClosure(1000);
      print(myadderone(0.5));
      print(myadderthousand(1));
      print(myadderthousand(2));

It evals to 1.5, 2 and 3, whereas it should be 1.5, 1001 and 1002.

The problem is that the inner function gets x=1 during the assignment 
myadderone = makeClosure(1);,
which is a correct behavior, but then x=1 value remains  when 
myadderthousand = makeClosure(1000);
is executed, which is wrong. 
Somehow crEnv in Function Object does not get created anew and that first environment with x=1 becomes forever attached to the inner function func.

**Comment by sumukhbarve** [comment]
Hi @hyperboloid77!

Thanks for pointing this out. The issue should now be resolved.

Added Test-30 to tests.py:
```js
        var mkAddX = null, add1 = null, add100 = null;
        mkAddX = function (x) {
            return function (n) {
                return x + n;
            };
        };
        add1 = mkAddX(1);
        add100 = mkAddX(100);
        print (add1(1) === 2 && add100(100) === 200); // ==> true
```

There was a bug related to AST cloning. Parsed functions were being being shallow-copied as opposed to being deep-cloned. Please confirm that the current update resolves the issue.

### Other details:
- Transferred repository ownership from @sumukhbarve to @polydojo.
- Changed license from MIT to MPL 2.0. It's still open source, just under a different license.

## Also, may we ask as to where/how you are using Jispy?

If you have any other queries, please feel free to raise an issue or write to bugs@polydojo.com.

**Comment by aabbtree77** [comment]
Yes, the code is good now. I am impressed how quickly you were able to fix this bug!

P.S. I am strictly an amateur, use Jispy to self-educate in PL implementations, I was mostly looking for a simple complete implementation of a minimal realistic modern language from scratch (without parser generators, VM and GC), and could not find anything but endless compiler books that are just about premature optimizations and which implement some mini-Pascal or C minus at best, or rather complex implementations that perhaps once used to be minimal, but are no longer such (Tcl, Lua, Smalltalk/Self/Io etc). 

So far I must say there are only two such projects: Jispy (LittleJ), and the Monkey language by Thorsten Ball. The latter looks somewhat easier for me to follow, there is no copying of trees when invoking a function and no use of exceptions needed to execute a return, MIT licence and already quite a few improved forks on various fronts (unicode etc.). I would say that code base is probably taking away all the attention from Jispy because it's way more visible, arguably golang vs Python 2.7 might also play a role, Thorsten Ball also wrote a book on his interpreter, and he appeared in a few well known podcasts. So it's a very similar Js-like language, but more effort on the documentation and marketing.

The interesting aspect about Jispy is that it stays close to the "good parts of Js", and you have some disposal of problems and improvements. However, that "single var" restriction "did not click" well for me because it's a bit of going into C89 style of coding when you have to declare all these nuisance temporaries, e.g. some iterator index "i" is not that important to be thought about and declared somewhere at the top only to be used in a simple for loop later. Also this potentially causes writing var func=null too often at the top, or long chains of function declarations separated by commas just because only one big long var statement is allowed. 

Anyway, this is my subjective opinion, and thank you for your really good work. You are probably my second hero in the entire world in terms of PL implementation. BTW, there is also a typo in "Crockfork" in DEDICATION.md.

**Comment by sumukhbarve** [comment]
Hello @hyperboloid77,

Thanks for getting back. Your candid response is sincerely appreciated.

At the time when Jispy was first written, somewhere in 2014, I was still a college student.
Were I to do it all over again, the code would be much more readable.

During Jispy's conception, ES6 wasn't quite around. We only had ES5. Had we looked at ES6, we probably would've disallowed `var` in favor of `let`. That'd remove the singe `var` requirement.

Another way of curtailing the `var` problem is by using a single container object per scope.
Initialize a variable as an object and then define multiple properties on that object.

Another thing. 'Cloning' essentially involves slicing a list. It isn't complicated.
For eg., in the prior-referenced test code, `add100`'s tree is a clone of `add1`'s tree.

When it comes to our (lack of) marketing, you are right. We must do better.
Our interns have now been tasked with improving Jispy's docs.

Our CTO is interested in re-writing Jispy, with a view to introduce the following:
- Unicode support. (Should be simple. Essentially, replace `str` with `unicode`.)
- Structural parsing. (That'll resolve the phony `&&`, `||` and trailing dots issues.)

Thanks and regards,
Sumukh
