### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by oden3000** [polydojo/jispy#2]
Looking to include this work into another project but you do not have any releases or tags. This would mean adding a commit into the `requirements.txt` file which is not a big deal but is undesirable.

Is there any reason for not have a release? To be honest it is a negative of the project as it implies it is not ready for use.

**Comment by sumukhbarve** [comment]
Hi @oden65!

We've introduced v1.0.0.

There was no (good) reason behind not having a release. You are right; not having a release reflects poorly on the project. Thanks for prodding us into remedying the situation.

We're glad that you plan on using Jispy. Would like to know more about your wonderful project.

Thanks and regards,
Sumukh

**Comment by oden3000** [comment]
Hi Sumukh,

Thank you for acting on this so quickly. 

We will be using this in a configuration management tool called [InProd](http://www.inprod.io). It will allow end users to create custom scripts within the application.
